/* AppIcons  */

export declare const appAt: string;
export declare const appCalendar1: string;
export declare const appCalendarSearch: string;
export declare const appCamera: string;
export declare const appChat: string;
export declare const appChevronDown: string;
export declare const appChevronLeft: string;
export declare const appChevronRight: string;
export declare const appChevronUp: string;
export declare const appClock: string;
export declare const appClose: string;
export declare const appCopy: string;
export declare const appCup: string;
export declare const appDoc: string;
export declare const appDownload: string;
export declare const appExit: string;
export declare const appGallery: string;
export declare const appInstagram: string;
export declare const appLetter: string;
export declare const appLoader: string;
export declare const appMapPoint: string;
export declare const appMedal: string;
export declare const appPen: string;
export declare const appPhone: string;
export declare const appPin: string;
export declare const appQrCode: string;
export declare const appQuestion: string;
export declare const appSettings: string;
export declare const appStarFill: string;
export declare const appStar: string;
export declare const appTelegram: string;
export declare const appTicket: string;
export declare const appTiktok: string;
export declare const appTrash: string;
export declare const appUser: string;
export declare const appWhatsapp: string;
export declare const appYoutube: string;
export declare const appTariffCard: string;

export type IconKey = 'appAt' | 'appCalendar1' | 'appCalendarSearch' | 'appCamera' | 'appChat' | 'appChevronDown' | 'appChevronLeft' | 'appChevronRight' | 'appChevronUp' | 'appClock' | 'appClose' | 'appCopy' | 'appCup' | 'appDoc' | 'appDownload' | 'appExit' | 'appGallery' | 'appInstagram' | 'appLetter' | 'appLoader' | 'appMapPoint' | 'appMedal' | 'appPen' | 'appPhone' | 'appPin' | 'appQrCode' | 'appQuestion' | 'appSettings' | 'appStarFill' | 'appStar' | 'appTelegram' | 'appTicket' | 'appTiktok' | 'appTrash' | 'appUser' | 'appWhatsapp' | 'appYoutube' | 'appTariffCard';
